export const UNIT_LIST_REQUEST = "UNIT_LIST_REQUEST";
export const UNIT_LIST_SUCCESS = "UNIT_LIST_SUCCESS";
export const UNIT_LIST_FAIL = "UNIT_LIST_FAIL";

export const USER_UNIT_LIST_REQUEST = "USER_UNIT_LIST_REQUEST";
export const USER_UNIT_LIST_SUCCESS = "USER_UNIT_LIST_SUCCESS";
export const USER_UNIT_LIST_FAIL = "USER_UNIT_LIST_FAIL";

export const CLEAR_UNITS_USER_SIGNOUT = "CLEAR_UNITS_USER_SIGNOUT";

export const ADD_SELECTED_UNIT = "ADD_SELECTED_UNIT";
export const REMOVE_SELECTED_UNIT = "REMOVE_SELECTED_UNIT";

export const UNIT_SELECTED = "UNIT_SELECTED";
export const UNIT_SENSORVALUES_REQUEST = "UNIT_SENSORVALUES_REQUEST";
export const UNIT_SENSORVALUES_SUCCESS = "UNIT_SENSORVALUES_SUCCESS";
export const UNIT_SENSORVALUES_FAIL = "UNIT_SENSORVALUES_FAIL";